import { theme } from '../theme'

export const appStyles = {
  page: {
    minHeight: '100vh',
    backgroundColor: theme.colors.appBackground,
    color: theme.colors.textPrimary,
    width: '100%',
  },
  header: {
    position: 'sticky' as const,
    top: 0,
    zIndex: 10,
    backgroundColor: theme.colors.appBackground,
    borderBottom: `1px solid ${theme.colors.borderMuted}`,
    width: '100%',
  },
  headerInner: {
    maxWidth: '100%',
    width: '100%',
    margin: '0 auto',
    padding: '12px 16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap' as const,
  },
  main: {
    maxWidth: 720,
    width: '100%',
    margin: '0 auto',
    padding: '16px 16px 24px',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 5,
    color: theme.colors.textPrimary,
  },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    flexWrap: 'wrap' as const,
    width: '100%',
  },
  toolbarRtl: {
    flexDirection: { xs: 'column', sm: 'row-reverse' } as const,
    alignItems: { xs: 'flex-start', sm: 'center' },
    gap: { xs: 1, sm: 16 },
  },
  title: {
    margin: 0,
    fontSize: '1.5rem',
    fontWeight: 700,
    whiteSpace: 'nowrap' as const,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    flex: '0 1 auto',
    maxWidth: '70%',
    minWidth: 0,
    width: { xs: '100%', sm: 'auto' },
  },
  titleRtl: {
    textAlign: 'right' as const,
  },
  brand: {
    display: 'flex',
    alignItems: 'center',
    gap: 2,
    minWidth: 0,
    cursor: 'pointer',
  },
  logo: {
    width: 64,
    height: 64,
    borderRadius: 6,
    objectFit: 'contain' as const,
  },
  sectionTitle: {
    margin: '12px 0 4px',
    fontSize: '1.25rem',
    fontWeight: 700,
  },
}
